#!/bin/bash

name=$1
private=$2

if [ -z "$2" ]
then
	private=false
fi

if [ $1 ]
then
	curl -H 'Authorization: token #TOKEN#' https://api.github.com/user/repos -d '{"name":"'"$name"'","private":'$private'}'
	git init
	git remote add origin https://github.com/"$(git config user.name)"/"$name".git
	touch .gitignore
	echo ""
	echo "Repository succesfully created"
else
	echo "Please input repository name"
fi
