#!/bin/bash

name=$1
private=$2
user="$(git config user.name)"

if [ $user == "" ]
then
	echo "Please set git username first by doing 'git config --global user.name YOUR_USERNAME'"
	exit
fi
if [ -z "$2" ]
then
	private=false
fi

if [ $1 ]
then
	curl -H 'Authorization: token #TOKEN#' https://api.github.com/user/repos -d '{"name":"'"$name"'","private":'$private'}'
	git init
	git remote add origin https://github.com/"$(git config user.name)"/"$name".git
	touch .gitignore
	echo ""
	echo "Repository succesfully created"
else
	echo "Please input repository name"
fi
